name: Build linux-amlogic
on:
  push:
  pull_request:
    paths:
      - 'linux-amlogic/**'

jobs:
  linux-amlogic:
    env:
      BUILD_DIR: /tmp/${{ github.job }}
    runs-on: ubuntu-latest
    container:
      image: archlinux:base-devel
    steps:
    - uses: actions/checkout@v2
    - name: Fix glibc
      run: curl -fsSL https://repo.archlinuxcn.org/x86_64/glibc-linux4-2.33-5-x86_64.pkg.tar.zst | bsdtar -C / -xvf -
    - name: Update packages
      run: yes | pacman -Syu --noconfirm
    - name: Install need packages
      run: yes | pacman -S --noconfirm --needed aarch64-linux-gnu-gcc
    - name: Allow nobody to execute sudo without a password
      run: 'echo "nobody ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers'
    - name: Copy Files
      run: |
        cp -rv "$GITHUB_WORKSPACE/${{ github.job }}" "${{ env.BUILD_DIR }}"
        chown -Rv nobody:root "${{ env.BUILD_DIR }}"
    - name: Make
      run: |
        pushd "${{ env.BUILD_DIR }}"
        sudo -u nobody env \
        ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- KBUILD_BUILD_HOST=github KBUILD_BUILD_USER=${{ github.repository_owner }} \
        makepkg --syncdeps --noconfirm --config "$GITHUB_WORKSPACE/makepkg.conf"
        pushd
    - name: List Files
      run: ls -l ${{ env.BUILD_DIR }}
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: ${{ github.job }}
        path: ${{ env.BUILD_DIR }}/*.pkg.tar.*
